### ISSUE TITLE
Set a different number of Clients when using LEAF dataset

### ISSUE THREAD

**Issue by ChristianInterno** [vaseline555/Federated-Learning-in-PyTorch#11]
First of all, amazing work! :)
There is a way to set a different number of Clients when using LEAF dataset? For example if I use FEMNIST fro LEAF the number of clients is 3597. Is possible to modify this for time and resources issue?

Thanks a lot!

**Comment by vaseline555** [comment]
Dear @ChristianInterno ,
Thank you for your warm comment!

You can adjust the number of clients for LEAF dataset by modifying `rawsmpl` argument smaller than 1.
For example, when passing as `--rawsmpl 0.1`, only 10% of the whole clients, about 360 clients, are sampled.
Please note that you have to remove all subdirectories EXCEPT `raw` (if it exists) under the directory where FEMNIST is located (e.g., `./data/femnist`), before adjusting the argument.

Hope this helps!
Have a good day 😃
Thank you.



Best,
Adam

**Comment by Jinfeng-Xu** [comment]
Fantastic work! 
I'm a freshman in the FL field.
When I use your project, it raises an error about unmatched size for inputs and outputs. 
'ValueError: Using a target size (torch.Size([10])) that is different to the input size (torch.Size([10, 10])) is deprecated. Please ensure they have the same size.' 
Here are the arguments, hoping to get your help.
python3 main.py --exp_name test --dataset MNIST --split_type iid --model_name LeNet --algorithm fedavg --eval_type=both --eval_metrics acc1 acc5 f1 precision recall --optimizer SGD --lr 0.01 --criterion BCELoss 
Many thanks.

Kindest regards,
Jinfeng
