### ISSUE TITLE
Client Multithreading is actually not Working.

### ISSUE THREAD

**Issue by imguangyu** [vaseline555/Federated-Learning-in-PyTorch#15]
Here is a fix provided by ChatGPT:

The way your code is structured right now, it submits one job to the `ThreadPoolExecutor` and then immediately waits for the result of that job before proceeding to the next iteration of the loop. This is due to the `.result()` call right after the `.submit()` call, which blocks the execution until the future is done and returns the result.

If you want to run the tasks in parallel, you should submit all the tasks first, and then wait for the results. Here is how you can adjust your code to do that:

```python
results = []
futures = []

with concurrent.futures.ThreadPoolExecutor(max_workers=min(len(ids), os.cpu_count() - 1)) as workhorse:
    for idx in TqdmToLogger(ids, logger=logger, desc=f'[{self.args.algorithm.upper()}] [Round: {str(self.round).zfill(4)}] ...update clients... ', total=len(ids)):
        future = workhorse.submit(__update_clients, self.clients[idx])
        futures.append(future)

    for future in concurrent.futures.as_completed(futures):
        result = future.result()
        results.append(result)
```

In this code snippet, all the tasks are first submitted to the executor and their corresponding Future objects are stored in the `futures` list. The `concurrent.futures.as_completed(futures)` function is then used to yield the futures as they are completed, and the results are retrieved and stored in the `results` list.

This way, the tasks will run in parallel (up to the number specified by `max_workers`), and you can collect the results as they become available.

**Comment by vaseline555** [comment]
Dear @imguangyu ,
Thank you for your valuable point!
(... and sorry for late reply)

Oops, I didn't even notice this situation
(TBH, I've once implemented this repo. with `ray`, but to minimize dependency on other package, I naively translated into `ThreadPoolExecutor`... yes, it was a spaghetti code 👎)

I wonder if you've tried with the code snippet that ChatGPT suggested.
Upon that modification, is the multi-threading work as expected?

I'll reflect your hotfix ASAP.
Thank you!

**Comment by imguangyu** [comment]
@vaseline555 I've tested the updated version, and they work as expected now.

**Comment by imguangyu** [comment]
Closed by mistake.

**Comment by vaseline555** [comment]
Thank you for your clarification @imguangyu !
This fix is to be reflected in this week.
Hope you have a nice week.
고마워요~

**Comment by vaseline555** [comment]
Your correction is now reflected! 
Thank you again. 😄
