### ISSUE TITLE
我运行cifar10数据集出现错误，该怎么解决

### ISSUE THREAD

**Issue by zhujian129** [vaseline555/Federated-Learning-in-PyTorch#21]
![图片1](https://github.com/vaseline555/Federated-Learning-in-PyTorch/assets/145652767/d4453894-7572-4b86-b8d2-6407c79971d9)

**Comment by KennyHuang22** [comment]
试试把 --test_size 改成 0.2

在主要使用英文的Github repository里尽量用英文提问，不然的话被回答的几率不大。

祝好运！
