### ISSUE TITLE
undefined variable error

### ISSUE THREAD

**Issue by henry174Ajou** [vaseline555/Federated-Learning-in-PyTorch#3]
In "utils.py", modules of Torch Vision are imported by `from torchvision import datasets, transforms`.

However, in the line 106 of the same file, these modules are referred to by `torchvision.datasets`, but there is no variable named by `torchvision`.

I fixed it by rewrite the import statement by just `import torchvision`. Now it works.

**Comment by vaseline555** [comment]
Thank you for your report!
FYI, this repository will be changed into new one (i.e., ver 2.0) as soon.
Thank you.
