### ISSUE TITLE
Looking forward to the introduction, clear code on the CIFAR dataset!

### ISSUE THREAD

**Issue by realcly** [vaseline555/Federated-Learning-in-PyTorch#5]
Looking forward to the introduction, clear code on the CIFAR dataset! Thanks！

**Comment by vaseline555** [comment]
Thank you for your interests! 
I am now preparing a new version of this repo (expected to release on August).
There will be supports on new datasets including CIFAR10, CIFAR100, TinyImageNet, SVHN, KMNIST, EMNIST, QMNIST, Fashion-MNIST, and LEAF benchmark datasets (FEMNIST, Shakespeare, Sent140, Celeba, Reddit, Synthetic).
Could you please be more patient?
Thank you.

**Comment by realcly** [comment]
> Thank you for your interests! I am now preparing a new version of this repo (expected to release on August). There will be supports on new datasets including CIFAR10, CIFAR100, TinyImageNet, SVHN, KMNIST, EMNIST, QMNIST, Fashion-MNIST, and LEAF benchmark datasets (FEMNIST, Shakespeare, Sent140, Celeba, Reddit, Synthetic). Could you please be more patient? Thank you.

Thanks for sharing! Look forward to the opportunity to communicate and learn with you!
